### PR TITLE
Login Page Styling added

### PR DESCRIPTION
**Pull request by bhaveshgarg2000**
Optimised Login Page
Please Give me HacktobeFest Tag
Thank You

### CODE REVIEW

**Review by huamanraj — COMMENTED** [review]
the repo is updated so please do some required changes!

**Comment by bhaveshgarg2000** [comment]
Could pls elaborate @huamanraj

**Comment by huamanraj** [comment]
> Could pls elaborate @huamanraj

the repo architecture is changed so you have to make some changes in file poisoning and linking! then update the PR

**Comment by bhaveshgarg2000** [comment]
ok

**Comment by bhaveshgarg2000** [comment]
I have taken Git Pull but it is showing me Everything is Upto date
image

**Comment by huamanraj** [comment]
> I have taken Git Pull but it is showing me Everything is Upto date
> image
> image
> 

Try reclone the repo then commit changes!

**Comment by bhaveshgarg2000** [comment]
Sure I'll do it by 8

**Comment by bhaveshgarg2000** [comment]
Hii @huamanraj You can close this PR as I have created new Branch with name "garg"

**Pull request closed without merging**
