### PR TITLE
Add a good looking readme

### LINKED ISSUE #3: creating a amazing README for this repo!
create a repo that align with this website and hacktoberfest 2023!

### PR DESCRIPTION
**Pull request by mezotv**
This closes #3

### CODE REVIEW

**Review by huamanraj — CHANGES_REQUESTED** [review]
please Add some hacktoberfest related logo and description also!

**Comment by mezotv** [comment]
> please Add some hacktoberfest related logo and description also!

Sure where in the file do you want those to be?

**Comment by huamanraj** [comment]
In heading before the logo part and also remove the extra part in logo image
image

**Comment by mezotv** [comment]
> In heading before the logo part and also remove the extra part in logo image image

Alright I have fixed those!

**Comment by huamanraj** [comment]
> > In heading before the logo part and also remove the extra part in logo image image
> 
> Alright I have fixed those

Great Work Dominik 🚀

**Pull request merged**
